export const fallbackEvents = [
  {
    round: 1,
    name: "bahrain",
    event_name: "Bahrain Grand Prix",
    country: "Bahrain",
    location: "Sakhir",
    date: "2023-03-05",
    sessions: {
      fp1: "2023-03-03T11:30:00Z",
      fp2: "2023-03-03T15:00:00Z",
      fp3: "2023-03-04T11:30:00Z",
      qualifying: "2023-03-04T15:00:00Z",
      sprint: null,
      race: "2023-03-05T15:00:00Z",
    },
    winner: "Max Verstappen",
  },
  {
    round: 2,
    name: "saudi_arabia",
    event_name: "Saudi Arabian Grand Prix",
    country: "Saudi Arabia",
    location: "Jeddah",
    date: "2023-03-19",
    sessions: {
      fp1: "2023-03-17T13:30:00Z",
      fp2: "2023-03-17T17:00:00Z",
      fp3: "2023-03-18T13:30:00Z",
      qualifying: "2023-03-18T17:00:00Z",
      sprint: null,
      race: "2023-03-19T17:00:00Z",
    },
    winner: "Sergio Perez",
  },
  {
    round: 3,
    name: "australia",
    event_name: "Australian Grand Prix",
    country: "Australia",
    location: "Melbourne",
    date: "2023-04-02",
    sessions: {
      fp1: "2023-03-31T01:30:00Z",
      fp2: "2023-03-31T05:00:00Z",
      fp3: "2023-04-01T01:30:00Z",
      qualifying: "2023-04-01T05:00:00Z",
      sprint: null,
      race: "2023-04-02T05:00:00Z",
    },
    winner: "Max Verstappen",
  },
  {
    round: 4,
    name: "azerbaijan",
    event_name: "Azerbaijan Grand Prix",
    country: "Azerbaijan",
    location: "Baku",
    date: "2023-04-30",
    sessions: {
      fp1: "2023-04-28T09:30:00Z",
      fp2: "2023-04-28T13:00:00Z",
      fp3: "2023-04-29T09:30:00Z",
      qualifying: "2023-04-29T13:00:00Z",
      sprint: null,
      race: "2023-04-30T12:00:00Z",
    },
    winner: "Sergio Perez",
  },
  {
    round: 5,
    name: "miami",
    event_name: "Miami Grand Prix",
    country: "USA",
    location: "Miami",
    date: "2023-05-07",
    sessions: {
      fp1: "2023-05-05T18:30:00Z",
      fp2: "2023-05-05T22:00:00Z",
      fp3: "2023-05-06T16:30:00Z",
      qualifying: "2023-05-06T20:00:00Z",
      sprint: null,
      race: "2023-05-07T19:30:00Z",
    },
    winner: "Max Verstappen",
  },
  {
    round: 22,
    name: "abu_dhabi",
    event_name: "Abu Dhabi Grand Prix",
    country: "UAE",
    location: "Yas Marina",
    date: "2023-11-26",
    sessions: {
      fp1: "2023-11-24T09:30:00Z",
      fp2: "2023-11-24T13:00:00Z",
      fp3: "2023-11-25T10:30:00Z",
      qualifying: "2023-11-25T14:00:00Z",
      sprint: null,
      race: "2023-11-26T13:00:00Z",
    },
    winner: "Max Verstappen",
  },
]

export const fallbackDrivers = [
  {
    driver_number: "1",
    name: "Max Verstappen",
    abbreviation: "VER",
    team_name: "Red Bull Racing",
    country: "Netherlands",
    points: 575,
    championship_position: 1,
  },
  {
    driver_number: "11",
    name: "Sergio Perez",
    abbreviation: "PER",
    team_name: "Red Bull Racing",
    country: "Mexico",
    points: 285,
    championship_position: 2,
  },
  {
    driver_number: "44",
    name: "Lewis Hamilton",
    abbreviation: "HAM",
    team_name: "Mercedes",
    country: "United Kingdom",
    points: 234,
    championship_position: 3,
  },
  {
    driver_number: "14",
    name: "Fernando Alonso",
    abbreviation: "ALO",
    team_name: "Aston Martin",
    country: "Spain",
    points: 206,
    championship_position: 4,
  },
  {
    driver_number: "16",
    name: "Charles Leclerc",
    abbreviation: "LEC",
    team_name: "Ferrari",
    country: "Monaco",
    points: 200,
    championship_position: 5,
  },
  {
    driver_number: "4",
    name: "Lando Norris",
    abbreviation: "NOR",
    team_name: "McLaren",
    country: "United Kingdom",
    points: 195,
    championship_position: 6,
  },
  {
    driver_number: "55",
    name: "Carlos Sainz",
    abbreviation: "SAI",
    team_name: "Ferrari",
    country: "Spain",
    points: 192,
    championship_position: 7,
  },
  {
    driver_number: "63",
    name: "George Russell",
    abbreviation: "RUS",
    team_name: "Mercedes",
    country: "United Kingdom",
    points: 189,
    championship_position: 8,
  },
  {
    driver_number: "81",
    name: "Oscar Piastri",
    abbreviation: "PIA",
    team_name: "McLaren",
    country: "Australia",
    points: 97,
    championship_position: 9,
  },
  {
    driver_number: "18",
    name: "Lance Stroll",
    abbreviation: "STR",
    team_name: "Aston Martin",
    country: "Canada",
    points: 74,
    championship_position: 10,
  },
]

export const fallbackTeams = [
  {
    name: "Red Bull Racing",
    full_name: "Oracle Red Bull Racing",
    base: "Milton Keynes, United Kingdom",
    team_principal: "Christian Horner",
    technical_director: "Pierre Waché",
    drivers: [
      {
        number: "1",
        name: "Max Verstappen",
        abbreviation: "VER",
        country: "Netherlands",
      },
      {
        number: "11",
        name: "Sergio Perez",
        abbreviation: "PER",
        country: "Mexico",
      },
    ],
    points: 860,
    championship_position: 1,
    wins: 21,
    podiums: 38,
    poles: 14,
  },
  {
    name: "Ferrari",
    full_name: "Scuderia Ferrari",
    base: "Maranello, Italy",
    team_principal: "Frédéric Vasseur",
    technical_director: "Enrico Cardile",
    drivers: [
      {
        number: "16",
        name: "Charles Leclerc",
        abbreviation: "LEC",
        country: "Monaco",
      },
      {
        number: "55",
        name: "Carlos Sainz",
        abbreviation: "SAI",
        country: "Spain",
      },
    ],
    points: 406,
    championship_position: 2,
    wins: 1,
    podiums: 9,
    poles: 7,
  },
  {
    name: "Mercedes",
    full_name: "Mercedes-AMG PETRONAS F1 Team",
    base: "Brackley, United Kingdom",
    team_principal: "Toto Wolff",
    technical_director: "James Allison",
    drivers: [
      {
        number: "44",
        name: "Lewis Hamilton",
        abbreviation: "HAM",
        country: "United Kingdom",
      },
      {
        number: "63",
        name: "George Russell",
        abbreviation: "RUS",
        country: "United Kingdom",
      },
    ],
    points: 398,
    championship_position: 3,
    wins: 1,
    podiums: 8,
    poles: 1,
  },
  {
    name: "McLaren",
    full_name: "McLaren F1 Team",
    base: "Woking, United Kingdom",
    team_principal: "Andrea Stella",
    technical_director: "James Key",
    drivers: [
      {
        number: "4",
        name: "Lando Norris",
        abbreviation: "NOR",
        country: "United Kingdom",
      },
      {
        number: "81",
        name: "Oscar Piastri",
        abbreviation: "PIA",
        country: "Australia",
      },
    ],
    points: 302,
    championship_position: 4,
    wins: 0,
    podiums: 9,
    poles: 1,
  },
  {
    name: "Aston Martin",
    full_name: "Aston Martin Aramco Cognizant F1 Team",
    base: "Silverstone, United Kingdom",
    team_principal: "Mike Krack",
    technical_director: "Dan Fallows",
    drivers: [
      {
        number: "14",
        name: "Fernando Alonso",
        abbreviation: "ALO",
        country: "Spain",
      },
      {
        number: "18",
        name: "Lance Stroll",
        abbreviation: "STR",
        country: "Canada",
      },
    ],
    points: 280,
    championship_position: 5,
    wins: 0,
    podiums: 8,
    poles: 0,
  },
]
